App/complaint/models.py
from app import db
from user.models import User

class Complaint(db.Document):
    name = db.StringField(requiered=True)
    place = db.StringField(requiered=True)
    location = db.PointField(required=True)
    complaint_photo = db.StringField()
    description = db.StringField(required=True)
    complainer = db.ObjectIdField(requiered=True)
    cancel = db.BooleanField(default=False)
    follow = db.ListField(db.ReferenceField(User))
    



    

App/complaint/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, validators, DateTimeField, FloatField
from wtforms.widgets import TextArea
from flask_wtf.file import FileField, FileAllowed

class BasicComplaintForm(FlaskForm):
    name = StringField('Nombre Denuncia', validators=[validators.DataRequired()])
    gplace = StringField('Google Place Api')
    place = StringField('Place', widget= TextArea())
    lng = FloatField('Longitude', validators=[validators.Optional()])
    lat = FloatField('Latitude', validators=[validators.Optional()])
    description = StringField('Descripcion' , validators=[validators.DataRequired()])

class EditComplaintForm(BasicComplaintForm):
    photo = FileField('Complaint Photo', [FileAllowed(['jpg','jpeg','png'], 'Only allowed .jpg .png files')])

class CancelComplaintForm(FlaskForm):
    confirm = StringField('Are you sure do yo want to cancel this complaint? (Say "yes")', validators=[validators.DataRequired()])

App/complaint/views.py
### Controlador Modulo Complaint

from flask import Blueprint, render_template, request, session, redirect, url_for, abort 
import bson
from complaint.forms import BasicComplaintForm, EditComplaintForm, CancelComplaintForm
from user.decorators import login_required
from complaint.models import Complaint
from user.models import User
from utilities.storage import upload_image_file



complaint_page = Blueprint('complaint_page', __name__)

#Crear queja
@complaint_page.route('/create', methods=['GET','POST'])
@login_required
def create():
    #instancia formulario 
    form = BasicComplaintForm()
    error = None
    #validar formulario y post request
    if request.method == 'POST' and form.validate():
        error= form.errors
        print(error)
        if not error:
            #si el usuario tiene sesion activa
            user = User.objects.filter(email=session.get('email')).first()
           #almacenar en bd
            complaint= Complaint(
                name=form.name.data,
                place=form.place.data,
                location=[form.lng.data, form.lat.data],
                description = form.description.data,
                complainer= user.id,
                follow= [user]
            )
            complaint.save()
            return redirect(url_for('complaint_page.edit', id=complaint.id))
    return render_template('complaint/create.html', form=form)

#editar queja
@complaint_page.route('/<id>/edit', methods=['GET', 'POST'])
@login_required
def edit(id):
    try:
        #filtar id denuncia
        complaint = Complaint.objects.filter(id=bson.ObjectId(id)).first()
    except bson.errors.InvalidId:
        abort(404)     
        #si el usuario tiene sesion activa
    user = User.objects.filter(email=session.get('email')).first()
    if complaint and complaint.complainer == user.id:
        error = None
        message = None
        #instanciar formulario
        form = EditComplaintForm(obj=complaint)
        if request.method == 'POST' and form.validate():
            if not error:
                form.populate_obj(complaint)
                #tomar valores de latitud y longitud y guardarlos en un array 'location'
                if form.lng.data and form.lat.data:
                    complaint.location = [form.lng.data, form.lat.data]
                # guardar imagen denuncia 
                image_url = upload_image_file(request.files.get('photo'), 'complaint_photo', str(complaint.id))
                if image_url:
                    complaint.complaint_photo = image_url
                complaint.save()
                message = 'Complaint updated'
        return render_template('complaint/edit.html', form=form, error=error,
                              message=message, complaint=complaint)
    else:
        abort(404)

#cancelar queja
@complaint_page.route('/<id>/cancel', methods=['GET','POST'])
@login_required
def cancel(id):
    try:
        #filtrar id queja
        complaint = Complaint.objects.filter(id=bson.ObjectId(id)).first()
    except bson.errors.InvalidId:
        abort(404)
        #verificar sesion usuario
    user = User.objects.filter(email=session.get('email')).first()
    
    #si el denunciante y la queja tienen el mismo userid y /cancel desactivado
    if complaint and complaint.complainer == user.id and complaint.cancel == False:
        error = None
        form = CancelComplaintForm()
        if request.method == 'POST' and form.validate():
            #escribir yes para confirmar cancelacion
            if form.confirm.data == 'yes':
                complaint.cancel = True
                complaint.save()
                return redirect(url_for('complaint_page.edit', id=complaint.id))
            else:
                error = 'Say yes if you want to cancel'
        return render_template('complaint/cancel.html', form=form, error=error, complaint=complaint)
    else:
        abort(404)

#Mostrar Queja
@complaint_page.route('/<id>', methods=['GET'])
def public(id):
    try:
        #filtrar id queja
        complaint = Complaint.objects.filter(id=bson.ObjectId(id)).first()
    except bson.errors.InvalidId:
        abort(404)
        
        
    if complaint:
        complainer = User.objects.filter(id=complaint.complainer).first()
        user = User.objects.filter(email=session.get('email')).first()
        return render_template('complaint/public.html', complaint=complaint, complainer=complainer, user=user)
    else:
        abort(404)

#Apoyar denuncia
@complaint_page.route('/<id>/support', methods=['GET'])
@login_required
def support(id):
    user = User.objects.filter(email=session.get('email')).first()
    try:
        complaint = Complaint.objects.filter(id=bson.ObjectId(id)).first()
    except bson.errors.InvalidId:
        abort(404)    
    
    if user and complaint:
        if user not in complaint.follow:
            complaint.follow.append(user)
            complaint.save()
        return redirect(url_for('complaint_page.public', id=id))
    else:
        abort(404)

#dejar de apoyar las denuncias   
@complaint_page.route('/<id>/unsupport', methods=['GET'])
@login_required
def unsupport(id):
    user = User.objects.filter(email=session.get('email')).first()
    try:
        complaint = Complaint.objects.filter(id=bson.ObjectId(id)).first()
    except bson.errors.InvalidId:
        abort(404)   
    
    if user and complaint:
        if user in complaint.follow:
            complaint.follow.remove(user)
            complaint.save()
        return redirect(url_for('complaint_page.public', id=id))
    else:
        abort(404)

#listado de denuncias hechas (como usuario registrado)
@complaint_page.route('/manage/<int:complaint_page_number>', methods=['GET'])
@complaint_page.route('/manage', methods=['GET'])
@login_required
def manage(complaints_page_number=1):
    user = User.objects.filter(email=session.get('email')).first()
    if user:
        complaints = Complaint.objects.filter(complainer=user.id).order_by('name').paginate(page=complaints_page_number, per_page=4)
        return render_template('complaint/manage.html', complaints=complaints)
    else:
        abort(404)     

#Listado global de denuncias
@complaint_page.route('/explore/<int:complaint_page_number>', methods=['GET'])
@complaint_page.route('/explore', methods=['GET'])
def explore(complaint_page_number=1):
    place = request.args.get('place')
    try:
        lng = float(request.args.get('lng'))
        lat = float(request.args.get('lat'))
        complaints = Complaint.objects(location__near=[lng, lat], location__max_distance=100000,
                               cancel=False).paginate(page=complaint_page_number, per_page=4)
        return render_template('complaint/explore.html', complaints=complaints, place=place, lng=lng, lat=lat)
    except:
        return render_template('complaint/explore.html', place=place)

App/user/views.py
#controlador de modulo user
from flask import Blueprint, render_template, request, session, redirect, url_for, abort
from user.models import User
from user.forms import RegistrationForm, LoginForm, EditProfileForm, PasswordForm
import bcrypt
import bson
from user.decorators import login_required
from utilities.storage import upload_image_file



user_page = Blueprint('user_page', __name__)

#Iniciar Sesion
@user_page.route('/login', methods=['GET', 'POST'])
def login():
    form = LoginForm(request.form)
    error = None
        # si request es post y el formato ha sido validado compara el hash en la base de datos
    if request.method == 'POST' and form.validate():
        user = User.objects.filter(email=form.email.data.lower()).first()
        if user:
            if bcrypt.checkpw(form.password.data, user.password):
                session['email'] = user.email
                #return redirect(request.args.get('next') or url_for('home'))
                return redirect(url_for('complaint_page.explore'))
            else:
                user = None
        if not user:
            error = 'Your email or password was entered incorrectly'
    return render_template('user/login.html', form=form, error=error)

#Cerrar Sesion
@user_page.route('/logout')
def logout():
    session.pop('email')
    return redirect(url_for('user_page.login'))

# Registro de usuario
@user_page.route('/newuser', methods=['GET', 'POST'])
def signup():
    #instancia formulario de registro
    form = RegistrationForm(request.form)
    # si request es post y el formato ha sido validado registra el usuario
    if request.method == 'POST' and form.validate():
        salt = bcrypt.gensalt()
        hashed_password = bcrypt.hashpw(form.password.data, salt)   
        user = User(      
            name= form.name.data,
            lastname= form.lastname.data,
            city= form.city.data,
            email= form.email.data.lower(),
            password= hashed_password
        )
        user.save()
        return redirect(url_for('user_page.login'))
    return render_template('user/signup.html', form=form)

#Editar Usuario
@user_page.route('/edit', methods=['POST','GET'])
@login_required
def edit():
    #validar que inicio sesion
    user = User.objects.filter(email=session['email']).first()
    if user: 
        error = None
        message = None
        form = EditProfileForm(obj=user)

        #validar que los datos actualizados no esten en uso
        if request.method == 'POST' and form.validate():
            if user.email != form.email.data.lower():
                if User.objects.filter(email=form.email.data.lower()).first():
                    error = 'Email is already in use'
                else: 
                    session['email'] = form.email.data.lower()
            if not error:
                form.populate_obj(user)
                image_url = upload_image_file(request.files.get('image'), 'profile_image', str(user.id))
                print(str(request.files.get('image')))
                if image_url:
                    user.profile_image = image_url

                user.save()  
                message = 'Profile updated'

        return render_template('user/edit.html', user=user, form=form, error=error, message=message)
    else:
        abort(404)

#cambiar contraseña 
@user_page.route('/password', methods=['GET', 'POST'])
@login_required
def password():
    user = User.objects.filter(email=session.get('email')).first()
    if user:
        error = None
        message = None
        form = PasswordForm()
        if request.method == 'POST' and form.validate():
            if bcrypt.checkpw(form.old_password.data, user.password):
                salt = bcrypt.gensalt()
                hashed_password = bcrypt.hashpw(form.new_password.data, salt)
                user.password = hashed_password
                user.save()
                message = 'Password updated'
            else:
                error = 'Your old password was incorrect'
        return render_template('user/password.html', form=form, error=error, message=message)
    else:
        abort(404)


#Perfil usuario 
@user_page.route('/<id>')
def profile(id):
    try:
        user = User.objects.filter(id=bson.ObjectId(id)).first()
    except bson.errors.InvalidId:
        abort(404)
    if user:
        return render_template('user/profile.html', user=user)
    else:
        abort(404)
    

App/templates/complaint/cancel.html
{% extends "base.html" %}
{% block title %}Cancel this complaint {% endblock %}
{% block content %}
<div class="row">
    <div class="col-md-6 offset-md-3">
        <h3>
            {{ complaint.name }}
        </h3>
        
        {% if error %}
        <div class="alert alert-danger">
            {{ error }}
        </div>
        {% endif %}
        
        {% from "_formhelpers.html" import render_field %}
        <form method="POST" action="{{ url_for('complaint_page.cancel', id=complaint.id) }}">
            
            {{ form.csrf_token }}
            {{ render_field(form.confirm, class="form-control") }}
            
            <button type="submit" class="btn btn-danger">
                Cancel this Complaint
            </button>
        
            <a href="{{ url_for('complaint_page.edit', id=complaint.id) }}">back to edit complaint</a>
       
        </form>
    </div>
</div>
{% endblock %}

App/templates/complaint/create.html
{% extends "base.html" %}
{% block title %}Create Complaint{% endblock %}
{% block content %}

<div class="row">
    <div class="col-md-6 offset-md-3">
        <div class="text-center">
            <h3>
                Create Complaint
            </h3>
        </div>
        {% if error %}
        <div class="alert alert-danger">
            {{ error }}
        </div>
        {% endif %}
        
        {% from "_formhelpers.html" import render_field %}
        <form method="POST" action="{{ url_for('complaint_page.create')}}" >
            {{ form.csrf_token }}
            {{ render_field(form.name, class="form-control") }}
            {{ render_field(form.gplace, class="form-control", id="autocomplete", placeholder="Enter your address") }}
            {{ render_field(form.place, class="form-control", id="place", readonly=true) }}
            {{ render_field(form.lng, class="form-control", id="lng", readonly=true) }}
            {{ render_field(form.lat, class="form-control", id="lat", readonly=true) }}
            {{ render_field(form.description, class="form-control", rows="8", minlength="50") }}
            
            <button type="submit" class="btn btn-success">
                Create 
            </button>
        </form>
    </div>
</div>
{% endblock %}

{% block javascript %}
{% include "googleapi.html" %}
{% endblock %}

App/templates/complaint/edit.html
{% extends "base.html" %}
{% block title %}Edit Complaint{% endblock %}
{% block content %}

<div class="row">
    <div class="col-md-6 offset-md-3">
        
        {% if complaint.complaint_photo %}
        <img width="100%" src="{{ complaint.complaint_photo }}">
        {% else %}
        <img width="100%" src="{{ url_for('static', filename='img/complaint.png') }}">
        {% endif %}
        
        <div class="text-center">
            <h3>
                Edit Complaint
            </h3>
            <h6>
                <a href="{{ url_for('complaint_page.public', id=complaint.id) }}">See this complaint </a>
            </h6>
        </div>
        {% if error %}
        <div class="alert alert-danger">
            {{ error }}
        </div>
        {% endif %}
        
        {% if message %}
        <div class="alert alert-success">
            {{ message }}
        </div>
        {% endif %}
        
        {% from "_formhelpers.html" import render_field %}
        <form method="POST" action="{{ url_for('complaint_page.edit', id=complaint.id) }}" enctype="multipart/form-data">
            {{ form.csrf_token }}
            {{ render_field(form.name, class="form-control") }}
            {{ render_field(form.gplace, class="form-control", id="autocomplete", placeholder="Enter your address") }}
            {{ render_field(form.place, class="form-control", id="place", readonly=true) }}
            {{ render_field(form.lng, class="form-control", id="lng", readonly=true) }}
            {{ render_field(form.lat, class="form-control", id="lat", readonly=true) }}
            {{ render_field(form.photo, class="form-control") }}
            {{ render_field(form.description, class="form-control", rows="8", minlength="50") }}
            
            {% if complaint.cancel %}
           This complaint has been canceled
            {% else %}
            <button type="submit" class="btn btn-success">
                Save
            </button>
            <a href="{{ url_for('complaint_page.cancel', id=complaint.id) }}">Cancel this complaint </a>
            {% endif %}
        </form>
    </div>
</div>
{% endblock %}

{% block javascript %}
{% include "googleapi.html" %}
{% endblock %}

App/templates/complaint/explore.html
{% extends "base.html" %}
{% block title %} Explore {% endblock %}
{% block content %}

<div class="jumbotron text-center">
    <div class="container">
        <h1 class="jumbotron-heading">
            Find Complaints
        </h1>
        <p class="lead text-muted">
            Explore complaints around your zone.
        </p>
        
        <form method="GET" action="{{ url_for('complaint_page.explore') }}">
            <div class="input-group">
                <input type="text" class="form-control" placeholder="Search for place..."
                       id="autocomplete">
                <input type="hidden" name="place" id="place">
                <input type="hidden" name='lng' id="lng">
                <input type="hidden" name="lat" id="lat">
                <span class="input-group-btn">
                    <button class="btn btn-secondary" type="submit">
                        Search
                    </button>
                </span>
            </div>
        </form>
    </div>
    
</div>

{% if complaints and complaints.pages > 0 %}
<p class="text-muted text-center">
    Complaint near {{ place }}
</p>


<div class="row">
    {% for complaint in complaints.items %}
    <div class="col-md-6 complaint-item">
        <div class="card">
            <a href="{{ url_for('complaint_page.public', id=complaint.id) }}" target="_blank">
            {% if complaint.complaint_photo %}
            <img class="card-img-top complaint-photo-item" src="{{ complaint.complaint_photo}}">
            {% else %}
            <img class="card-img-top complaint-photo-item" src="{{ url_for('static', filename='img/complaint.png')}}">
            {% endif %}
            </a>
            <div class="card-block">
                <h4 class="card-title">
                    {{ complaint.name }}
                </h4>
                <p class="card-text">
                    {{ complaint.description[:150] }}
                </p>
                <p class="card-text">
                    <i class="fa fa-map-marker" aria-hidden="true"></i>
                    <a href="http://maps.google.com?q={{ complaint.place }}" target="_blank">
                    {{ complaint.place }}
                    </a>
                    <br>
                    <i class="fa fa-users" aria-hidden="true"></i>
                    {{ complaint.follow|length }} Support
                </p>
            </div>
        </div>
    </div>
    {% endfor %}
</div>

<div class="row justify-content-center">
    <ul class="pagination">
        {% if complaints.has_prev %}
        <li class="page-item">
            <a class="page-link" href="{{ url_for('complaint_page.explore',
            complaint_page_number=complaints.prev_num, place=place, lng=lng, lat=lat) }}">
                <span>&laquo;</span>
            </a>
        </li>
        {% endif %}
        <li class="page-item">
            <p class="page-link">
                Page {{ complaints.page }} of {{ complaints.pages }}
            </p>        
        </li>
        {% if complaints.has_next %}
        <li class="page-item">
            <a class="page-link" href="{{ url_for('complaint_page.explore', 
            complaint_page_number=complaints.next_num, place=place, lng=lng, lat=lat) }}">
                <span>&raquo;</span>
            </a>
        </li>
        {% endif %}
    </ul>
</div>
{% elif place %}
<p class="text-muted text-center">
    We couldn't find any complaints here :(
</p>

{% else %}
{% endif %}

{% endblock %}
{% block javascript %}
{% include "googleapi.html" %}
{% endblock %}

App/templates/complaint/manage.html
{% extends "base.html" %}
{% block title %}List Of Complaints{% endblock %}
{% block content %}

<h1>
    My Complaints 
</h1>

<div class="row">
    {% for complaint in complaints.items %}
    <div class="col-md-6 complaint-item">
        <div class="card">
            {% if complaint.complaint_photo %}
            <img class="card-img-top complaint-photo-item" src="{{ complaint.complaint_photo}}">
            {% else %}
            <img class="card-img-top complaint-photo-item" src="{{ url_for('static', filename='img/complaint.png')}}">
            {% endif %}
            <div class="card-block">
                <h4 class="card-title">
                    {{ complaint.name }}
                </h4>
                <p class="card-text">
                    {{ complaint.description[:150] }}
                </p>
                <p class="card-text">
                    <i class="fa fa-map-marker" aria-hidden="true"></i>
                    <a href="http://maps.google.com?q={{ complaint.place }}" target="_blank">
                    {{ complaint.place }}
                    </a>
                    <br>
                    
                    <i class="fa fa-users" aria-hidden="true"></i>
                    {{ complaint.follow |length }} Support
                </p>
                {% if complaint.cancel %}
                <button class="btn btn-danger">
                    Canceled
                </button>
                {% else %}
                <a href="{{ url_for('complaint_page.edit', id=complaint.id) }}" class="btn btn-success">
                    Edit
                </a>
                {% endif %}
            </div>
        </div>
    </div>
    {% endfor %}
</div>

<div class="row justify-content-center">
    <ul class="pagination">
        {% if complaints.has_prev %}
        <li class="page-item">
            <a class="page-link" href="{{ url_for('complaint_page.manage',
            complaint_page_number=complaints.prev_num) }}">
                <span>&laquo;</span>
            </a>
        </li>
        {% endif %}
        <li class="page-item">
            <p class="page-link">
                Page {{ complaints.page }} of {{ complaints.pages }}
            </p>        
        </li>
        {% if complaints.has_next %}
        <li class="page-item">
            <a class="page-link" href="{{ url_for('complaint_page.manage', 
            complaint_page_number=complaints.next_num) }}">
                <span>&raquo;</span>
            </a>
        </li>
        {% endif %}
    </ul>
</div>
{% endblock %}

App/templates/complaint/map.html
{% for i in position.items %}
{{ i.0 }}
{{ i.1 }}
    
{% endfor %}

App/templates/complaint/public.html
{% extends "base.html" %}
{% block title %}{{ complaint.name }}{% endblock %}
{% block content %}

<h3>
    {{ complaint.name }}
</h3>
<p class="text-muted">
    This complaint has been made by
    <a href="{{ url_for('user_page.profile', id=complaint.complainer) }}">{{ complainer.name }}</a>
    {% if session.email == complainer.email %}
    <a href="{{ url_for('complaint_page.edit', id=complaint.id) }}">Edit</a>
    {% endif %}
</p>

<div class="row">
    <div class="col-md-8">
        {% if complaint.complaint_photo %}
        <img width="100%" src="{{ complaint.complaint_photo }}">
        {% else %}
        <img width="100%" src="{{ url_for('static', filename='img/complaint.png') }}">
        {% endif %}
    </div>
    
    <div class="col-md-4">
    
        <h6>
            Complaint Place:
        </h6>
        <p>
            <i class="fa fa-map-marker" aria-hidden="true"></i>
            <a href="http://maps.google.com?q={{ complaint.place }}" target="_blank">
            {{ complaint.place }}
            </a>
        </p>

        
        {% if complaint.cancel %}
        This complaint has been canceled.
        {% elif session['email'] == complainer.email %}
        {% elif user in complaint.follow %}
        <a href="{{ url_for('complaint_page.unsupport', id=complaint.id) }}" class="btn btn-danger">Unsupport</a>
        {% else %}
        <a href="{{ url_for('complaint_page.support', id=complaint.id) }}" class="btn btn-success">Support</a>
        {% endif %}
    </div>
</div>

<hr>
<h3>
    Description
</h3>
<div class="row">
    <div class="col-md-12">
        <p>
            {{ complaint.description}}
        </p>
    </div>
</div>

<hr>
<h3>
    Support by
</h3>
<div class="row">
    {% for user in complaint.follow %}
    <div class="col-md-3 text-center">
        <a href="{{ url_for('user_page.profile', id=user.id) }}">
        {% if user.profile_image %}
            <img width="150px" height="150px" src="{{ user.profile_image }}"
                 class="img-thumbnail rounded-circle">
        {% else %}
            <img width="150px" height="150px" src="{{ url_for('static', filename='img/user.png')}}"
                 class="img-thumbnail rounded-circle">
        {% endif %}
            <p>
                {{ user.name }}
            </p>
        </a>
    </div>
    {% endfor %}
</div>
{% endblock %}