App/user/models.py
#modelo bd
from app import db
import datetime

class User(db.Document):
    name = db.StringField(required=True)
    lastname = db.StringField(required=True)
    city = db.StringField(required=True)
    email = db.StringField(required=True, unique=True)
    password = db.StringField(required=True)
    created = db.DateTimeField(default=datetime.datetime.now)
    bio = db.StringField(max_length=200)
    profile_image = db.StringField()

App/user/forms.py
from flask_wtf import FlaskForm
from wtforms import Form, StringField, PasswordField, validators, ValidationError
from wtforms.fields.html5 import EmailField
from user.models import User
from wtforms.widgets import TextArea
from flask_wtf.file import FileField, FileAllowed

class BaseUserForm(Form):
    name = StringField('Your Name', [validators.DataRequired(),validators.Length(min=2,max=30)])
    lastname = StringField('Your Last Name', [validators.DataRequired(),validators.Length(min=2,max=30)])
    city = StringField('Your City', [validators.DataRequired(),validators.Length(min=2,max=30)])
    email = EmailField('Email Adress', [validators.DataRequired(), validators.Email()])

class RegistrationForm(BaseUserForm): 
    password = PasswordField('New password', [
        validators.DataRequired(), 
        validators.EqualTo('confirm', message='password must match')])
    confirm = PasswordField('Repeat password')

    def validate_email(Form, field):
        if User.objects.filter(email=field.data.lower()).first():
            raise ValidationError('Email address alreay in use')

class EditProfileForm(BaseUserForm):
    bio = StringField('Bio', widget=TextArea(), validators=[validators.Length(max=200)])
    image = FileField('Profile image', [FileAllowed(['jpg','jpeg','png'], 'Only allowed .jpg .png files')])

class LoginForm(Form):
    email= EmailField('Email address', [validators.DataRequired(), validators.Email()])
    password = PasswordField('Password', [validators.DataRequired()])

class PasswordForm(FlaskForm):
    old_password = PasswordField('Old Password', [validators.DataRequired()])
    new_password = PasswordField('New Password', [validators.DataRequired(),
                                                 validators.EqualTo('confirm',
                                                                    message='Passwords must match')])
    confirm = PasswordField('Confirm Password')

App/user/views.py
#controlador de modulo user
from flask import Blueprint, render_template, request, session, redirect, url_for, abort
from user.models import User
from user.forms import RegistrationForm, LoginForm, EditProfileForm, PasswordForm
import bcrypt
import bson
from user.decorators import login_required
from utilities.storage import upload_image_file



user_page = Blueprint('user_page', __name__)

#Iniciar Sesion
@user_page.route('/login', methods=['GET', 'POST'])
def login():
    form = LoginForm(request.form)
    error = None
        # si request es post y el formato ha sido validado compara el hash en la base de datos
    if request.method == 'POST' and form.validate():
        user = User.objects.filter(email=form.email.data.lower()).first()
        if user:
            if bcrypt.checkpw(form.password.data, user.password):
                session['email'] = user.email
                #return redirect(request.args.get('next') or url_for('home'))
                return redirect(url_for('complaint_page.explore'))
            else:
                user = None
        if not user:
            error = 'Your email or password was entered incorrectly'
    return render_template('user/login.html', form=form, error=error)

#Cerrar Sesion
@user_page.route('/logout')
def logout():
    session.pop('email')
    return redirect(url_for('user_page.login'))

# Registro de usuario
@user_page.route('/newuser', methods=['GET', 'POST'])
def signup():
    #instancia formulario de registro
    form = RegistrationForm(request.form)
    # si request es post y el formato ha sido validado registra el usuario
    if request.method == 'POST' and form.validate():
        salt = bcrypt.gensalt()
        hashed_password = bcrypt.hashpw(form.password.data, salt)   
        user = User(      
            name= form.name.data,
            lastname= form.lastname.data,
            city= form.city.data,
            email= form.email.data.lower(),
            password= hashed_password
        )
        user.save()
        return redirect(url_for('user_page.login'))
    return render_template('user/signup.html', form=form)

#Editar Usuario
@user_page.route('/edit', methods=['POST','GET'])
@login_required
def edit():
    #validar que inicio sesion
    user = User.objects.filter(email=session['email']).first()
    if user: 
        error = None
        message = None
        form = EditProfileForm(obj=user)

        #validar que los datos actualizados no esten en uso
        if request.method == 'POST' and form.validate():
            if user.email != form.email.data.lower():
                if User.objects.filter(email=form.email.data.lower()).first():
                    error = 'Email is already in use'
                else: 
                    session['email'] = form.email.data.lower()
            if not error:
                form.populate_obj(user)
                image_url = upload_image_file(request.files.get('image'), 'profile_image', str(user.id))
                print(str(request.files.get('image')))
                if image_url:
                    user.profile_image = image_url

                user.save()  
                message = 'Profile updated'

        return render_template('user/edit.html', user=user, form=form, error=error, message=message)
    else:
        abort(404)

#cambiar contraseña 
@user_page.route('/password', methods=['GET', 'POST'])
@login_required
def password():
    user = User.objects.filter(email=session.get('email')).first()
    if user:
        error = None
        message = None
        form = PasswordForm()
        if request.method == 'POST' and form.validate():
            if bcrypt.checkpw(form.old_password.data, user.password):
                salt = bcrypt.gensalt()
                hashed_password = bcrypt.hashpw(form.new_password.data, salt)
                user.password = hashed_password
                user.save()
                message = 'Password updated'
            else:
                error = 'Your old password was incorrect'
        return render_template('user/password.html', form=form, error=error, message=message)
    else:
        abort(404)


#Perfil usuario 
@user_page.route('/<id>')
def profile(id):
    try:
        user = User.objects.filter(id=bson.ObjectId(id)).first()
    except bson.errors.InvalidId:
        abort(404)
    if user:
        return render_template('user/profile.html', user=user)
    else:
        abort(404)
    

App/templates/user/edit.html
{% extends 'base.html' %}
{% block title %}Edit Profile {% endblock  %}
{% block content %}
<div class="row">
    <div class="col-md-6 offset-md-3">
        <div class="text-center">
            {% if user.profile_image %}  
          
            <img width="150px" height="150px" src="{{ user.profile_image }}" class="img-thumbnail rounded-circle ">
           
            {% else %}
            <img width="150px" height="150px" src="{{ url_for('static', filename='img/user.png') }}" class="img-thumbnail rounded-circle ">
            
            <h3>
                Edit Profile
            </h3>
            {% endif %}
        </div>
        
        {% if error  %}
        <div class='alert alert-danger' role='alert'>
            {{ error }}
        </div>
        {% endif %}

        {% if message %}
        <div class="alert alert-success" role="alert">
            {{ message }}
        </div>
        {% endif %}

        {% from '_formhelpers.html' import render_field %}
        <form method='POST' action="{{url_for('user_page.edit') }}" enctype="multipart/form-data">
            {{ form.csrf_token }}
            {{ render_field(form.name, class='form-control') }}
            {{ render_field(form.lastname, class='form-control') }}
            {{ render_field(form.city, class='form-control') }}
            {{ render_field(form.email, class='form-control') }}
            {{ render_field(form.image, class='form-control') }}
            {{ render_field(form.bio, class='form-control') }}

            <button type="submit" class="btn btn-success"> Save </button>

        </form>


    </div>
</div>
{% endblock  %}

App/templates/user/login.html
{% extends 'base.html' %}
{% block title %} Login {% endblock  %}
{% block content %}
<div class='row'>
    <div class="col-md-6 offset-md-3">
        <h3>
            DenunciasApp: Login
        </h3>
        {% if error %}
         <div class="alert alert-danger">
             {{ error }}
         </div>
        {% endif %}

        {% from '_formhelpers.html' import render_field  %}
       <!-- <form method="POST" action="{{ url_for('user_page.login') }}"></form> -->
            <form method="POST">
            {{ form.csrf_token }}
            {{ render_field(form.email, class='form-control', placeholder='Enter your email')}}
            {{ render_field(form.password, class='form-control', placeholder='Enter your password')}} 
            <button type="submit" class="btn btn-success"> Login </button>

        </form>
    </div>
</div>
{% endblock  %}

App/templates/user/password.html
{% extends "base.html" %}
{% block title %}Change Your Password{% endblock %}
{% block content %}
<div class="row">
    <div class="col-md-6 offset-md-3">
        <div class="text-center">
            <h3>
                Change Your Password
            </h3>            
        </div>
        {% if error %}
        <div class="alert alert-danger" role="alert">
            {{ error }}
        </div>
        {% endif %}
        {% if message %}
        <div class="alert alert-success" role="alert">
            {{ message }}
        </div>
        {% endif %}
        
        {% from "_formhelpers.html" import render_field %}
        <form method="POST" action="{{ url_for('user_page.password')}}">
            
            {{ form.csrf_token }}
            {{ render_field(form.old_password, class="form-control") }}
            {{ render_field(form.new_password, class="form-control") }}
            {{ render_field(form.confirm, class="form-control") }}
            
            <button type="submit" class="btn btn-success">
                Update Password
            </button>
        </form>
    </div>
</div>
{% endblock %}

App/templates/user/profile.html
{% extends 'base.html' %}
{% block title %}
{{ user.name }} Perfil 

{% block content %}
<div class="row">
    <div class="col-md-6 offset-md-3">
        <div class="text-center">
            {% if user.profile_image %}
            <img width="150px" height="150px" src="{{ user.profile_image }}" class="img-thumbnail rounded-circle">
            {% else %}
            <img width="150px" height="150px" src="{{ url_for('static', filename='img/user.png') }}" class="img-thrumbnail rounded-circle">
            {% endif %}
            <h3>
                {{ user.name }}
            </h3>
            
            <p>
                {% if user.bio %}
                {{ user.bio }}
                {% else %}
                Hello everyone, I am a newbie here!
                {% endif %}
            </p>
        </div>
    </div>   
</div>
{% endblock  %}
    
{% endblock %}

App/templates/user/signup.html
{% extends "base.html"  %}

{% block title  %} Signup {% endblock  %}

{% block content %}
<div class="row">
    <div class="col-md-6 offset-md-3">
        <h3>Signup</h3>
        {% from '_formhelpers.html' import render_field %}
        <form method="POST" action="{{ url_for('user_page.signup') }}">
            {{ form.crsf_token }}
            {{ render_field(form.name, class='form-control', placeholder='enter your name') }}
            {{ render_field(form.lastname, class='form-control', placeholder='enter your last name') }}
            {{ render_field(form.city, class='form-control', placeholder='enter your city') }}
            {{ render_field(form.email, class='form-control', placeholder='enter your email') }}
            {{ render_field(form.password, class='form-control', placeholder='enter your password') }}
            {{ render_field(form.confirm, class='form-control', placeholder='enter your password again to confirm') }}
            <button type="submit" class="btn btn-success"> Signup </button>
        </form>

        
    </div>
</div>
{% endblock  %}