App/complaint/views.py
### Controlador Modulo Complaint

from flask import Blueprint, render_template, request, session, redirect, url_for, abort 
import bson
from complaint.forms import BasicComplaintForm, EditComplaintForm, CancelComplaintForm
from user.decorators import login_required
from complaint.models import Complaint
from user.models import User
from utilities.storage import upload_image_file



complaint_page = Blueprint('complaint_page', __name__)

#Crear queja
@complaint_page.route('/create', methods=['GET','POST'])
@login_required
def create():
    #instancia formulario 
    form = BasicComplaintForm()
    error = None
    #validar formulario y post request
    if request.method == 'POST' and form.validate():
        error= form.errors
        print(error)
        if not error:
            #si el usuario tiene sesion activa
            user = User.objects.filter(email=session.get('email')).first()
           #almacenar en bd
            complaint= Complaint(
                name=form.name.data,
                place=form.place.data,
                location=[form.lng.data, form.lat.data],
                description = form.description.data,
                complainer= user.id,
                follow= [user]
            )
            complaint.save()
            return redirect(url_for('complaint_page.edit', id=complaint.id))
    return render_template('complaint/create.html', form=form)

#editar queja
@complaint_page.route('/<id>/edit', methods=['GET', 'POST'])
@login_required
def edit(id):
    try:
        #filtar id denuncia
        complaint = Complaint.objects.filter(id=bson.ObjectId(id)).first()
    except bson.errors.InvalidId:
        abort(404)     
        #si el usuario tiene sesion activa
    user = User.objects.filter(email=session.get('email')).first()
    if complaint and complaint.complainer == user.id:
        error = None
        message = None
        #instanciar formulario
        form = EditComplaintForm(obj=complaint)
        if request.method == 'POST' and form.validate():
            if not error:
                form.populate_obj(complaint)
                #tomar valores de latitud y longitud y guardarlos en un array 'location'
                if form.lng.data and form.lat.data:
                    complaint.location = [form.lng.data, form.lat.data]
                # guardar imagen denuncia 
                image_url = upload_image_file(request.files.get('photo'), 'complaint_photo', str(complaint.id))
                if image_url:
                    complaint.complaint_photo = image_url
                complaint.save()
                message = 'Complaint updated'
        return render_template('complaint/edit.html', form=form, error=error,
                              message=message, complaint=complaint)
    else:
        abort(404)

#cancelar queja
@complaint_page.route('/<id>/cancel', methods=['GET','POST'])
@login_required
def cancel(id):
    try:
        #filtrar id queja
        complaint = Complaint.objects.filter(id=bson.ObjectId(id)).first()
    except bson.errors.InvalidId:
        abort(404)
        #verificar sesion usuario
    user = User.objects.filter(email=session.get('email')).first()
    
    #si el denunciante y la queja tienen el mismo userid y /cancel desactivado
    if complaint and complaint.complainer == user.id and complaint.cancel == False:
        error = None
        form = CancelComplaintForm()
        if request.method == 'POST' and form.validate():
            #escribir yes para confirmar cancelacion
            if form.confirm.data == 'yes':
                complaint.cancel = True
                complaint.save()
                return redirect(url_for('complaint_page.edit', id=complaint.id))
            else:
                error = 'Say yes if you want to cancel'
        return render_template('complaint/cancel.html', form=form, error=error, complaint=complaint)
    else:
        abort(404)

#Mostrar Queja
@complaint_page.route('/<id>', methods=['GET'])
def public(id):
    try:
        #filtrar id queja
        complaint = Complaint.objects.filter(id=bson.ObjectId(id)).first()
    except bson.errors.InvalidId:
        abort(404)
        
        
    if complaint:
        complainer = User.objects.filter(id=complaint.complainer).first()
        user = User.objects.filter(email=session.get('email')).first()
        return render_template('complaint/public.html', complaint=complaint, complainer=complainer, user=user)
    else:
        abort(404)

#Apoyar denuncia
@complaint_page.route('/<id>/support', methods=['GET'])
@login_required
def support(id):
    user = User.objects.filter(email=session.get('email')).first()
    try:
        complaint = Complaint.objects.filter(id=bson.ObjectId(id)).first()
    except bson.errors.InvalidId:
        abort(404)    
    
    if user and complaint:
        if user not in complaint.follow:
            complaint.follow.append(user)
            complaint.save()
        return redirect(url_for('complaint_page.public', id=id))
    else:
        abort(404)

#dejar de apoyar las denuncias   
@complaint_page.route('/<id>/unsupport', methods=['GET'])
@login_required
def unsupport(id):
    user = User.objects.filter(email=session.get('email')).first()
    try:
        complaint = Complaint.objects.filter(id=bson.ObjectId(id)).first()
    except bson.errors.InvalidId:
        abort(404)   
    
    if user and complaint:
        if user in complaint.follow:
            complaint.follow.remove(user)
            complaint.save()
        return redirect(url_for('complaint_page.public', id=id))
    else:
        abort(404)

#listado de denuncias hechas (como usuario registrado)
@complaint_page.route('/manage/<int:complaint_page_number>', methods=['GET'])
@complaint_page.route('/manage', methods=['GET'])
@login_required
def manage(complaints_page_number=1):
    user = User.objects.filter(email=session.get('email')).first()
    if user:
        complaints = Complaint.objects.filter(complainer=user.id).order_by('name').paginate(page=complaints_page_number, per_page=4)
        return render_template('complaint/manage.html', complaints=complaints)
    else:
        abort(404)     

#Listado global de denuncias
@complaint_page.route('/explore/<int:complaint_page_number>', methods=['GET'])
@complaint_page.route('/explore', methods=['GET'])
def explore(complaint_page_number=1):
    place = request.args.get('place')
    try:
        lng = float(request.args.get('lng'))
        lat = float(request.args.get('lat'))
        complaints = Complaint.objects(location__near=[lng, lat], location__max_distance=100000,
                               cancel=False).paginate(page=complaint_page_number, per_page=4)
        return render_template('complaint/explore.html', complaints=complaints, place=place, lng=lng, lat=lat)
    except:
        return render_template('complaint/explore.html', place=place)

App/user/views.py
#controlador de modulo user
from flask import Blueprint, render_template, request, session, redirect, url_for, abort
from user.models import User
from user.forms import RegistrationForm, LoginForm, EditProfileForm, PasswordForm
import bcrypt
import bson
from user.decorators import login_required
from utilities.storage import upload_image_file



user_page = Blueprint('user_page', __name__)

#Iniciar Sesion
@user_page.route('/login', methods=['GET', 'POST'])
def login():
    form = LoginForm(request.form)
    error = None
        # si request es post y el formato ha sido validado compara el hash en la base de datos
    if request.method == 'POST' and form.validate():
        user = User.objects.filter(email=form.email.data.lower()).first()
        if user:
            if bcrypt.checkpw(form.password.data, user.password):
                session['email'] = user.email
                #return redirect(request.args.get('next') or url_for('home'))
                return redirect(url_for('complaint_page.explore'))
            else:
                user = None
        if not user:
            error = 'Your email or password was entered incorrectly'
    return render_template('user/login.html', form=form, error=error)

#Cerrar Sesion
@user_page.route('/logout')
def logout():
    session.pop('email')
    return redirect(url_for('user_page.login'))

# Registro de usuario
@user_page.route('/newuser', methods=['GET', 'POST'])
def signup():
    #instancia formulario de registro
    form = RegistrationForm(request.form)
    # si request es post y el formato ha sido validado registra el usuario
    if request.method == 'POST' and form.validate():
        salt = bcrypt.gensalt()
        hashed_password = bcrypt.hashpw(form.password.data, salt)   
        user = User(      
            name= form.name.data,
            lastname= form.lastname.data,
            city= form.city.data,
            email= form.email.data.lower(),
            password= hashed_password
        )
        user.save()
        return redirect(url_for('user_page.login'))
    return render_template('user/signup.html', form=form)

#Editar Usuario
@user_page.route('/edit', methods=['POST','GET'])
@login_required
def edit():
    #validar que inicio sesion
    user = User.objects.filter(email=session['email']).first()
    if user: 
        error = None
        message = None
        form = EditProfileForm(obj=user)

        #validar que los datos actualizados no esten en uso
        if request.method == 'POST' and form.validate():
            if user.email != form.email.data.lower():
                if User.objects.filter(email=form.email.data.lower()).first():
                    error = 'Email is already in use'
                else: 
                    session['email'] = form.email.data.lower()
            if not error:
                form.populate_obj(user)
                image_url = upload_image_file(request.files.get('image'), 'profile_image', str(user.id))
                print(str(request.files.get('image')))
                if image_url:
                    user.profile_image = image_url

                user.save()  
                message = 'Profile updated'

        return render_template('user/edit.html', user=user, form=form, error=error, message=message)
    else:
        abort(404)

#cambiar contraseña 
@user_page.route('/password', methods=['GET', 'POST'])
@login_required
def password():
    user = User.objects.filter(email=session.get('email')).first()
    if user:
        error = None
        message = None
        form = PasswordForm()
        if request.method == 'POST' and form.validate():
            if bcrypt.checkpw(form.old_password.data, user.password):
                salt = bcrypt.gensalt()
                hashed_password = bcrypt.hashpw(form.new_password.data, salt)
                user.password = hashed_password
                user.save()
                message = 'Password updated'
            else:
                error = 'Your old password was incorrect'
        return render_template('user/password.html', form=form, error=error, message=message)
    else:
        abort(404)


#Perfil usuario 
@user_page.route('/<id>')
def profile(id):
    try:
        user = User.objects.filter(id=bson.ObjectId(id)).first()
    except bson.errors.InvalidId:
        abort(404)
    if user:
        return render_template('user/profile.html', user=user)
    else:
        abort(404)
    

App/templates/_formhelper.html
{% macro render_field(field) %}
<div class="form-group">
    {{ field.label }}
    {{ field(**kwargs) | safe }}
    {% if field.errors %}
        <ul class="text-danger">
        {% for error in field.errors %}
            <li> {{ error }}</li>
        {% endfor %}}
        </ul>  
        {% endif %}      
</div>
{% endmacro %}

App/templates/_formhelpers.html
{% macro render_field(field) %}
<div class="form-group">
    {{ field.label }}
    {{ field(**kwargs)|safe }}
    {% if field.errors %}
        <ul class="text-danger">
        {% for error in field.errors %}
            <li> {{ error }}</li>
        {% endfor %}}
        </ul>  
    {% endif %}      
</div>
{% endmacro %}

App/templates/base.html
<!-- saved from url=(0266)https://mp4-a.udemycdn.com/2018-08-20_12-24-33-2277d31cc9916dcdc91ec5c549853b24/original.html?HZw0fwoxYRV3yENbkf_wAVHIprDOUQkYFCn1q8_Vk9yqN8RbVq6fovQKXdjY_4AtaAf8GAw9Mol7PqBisVjlz9QLL6aain8399fij693A-QSSwf4T3wo6RZfAodAyh3VPO3TAqNrzfYqQhGGnuPEa-C8akZbmwMUr5HgBSNvZjL3 -->
<html lang="en">
  <head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
  
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
  
    <title> {% block titel %} {%endblock%}</title>
  
    <!-- Bootstrap core CSS -->
    <link href="https://stackpath.bootstrapcdn.com/bootswatch/4.5.0/minty/bootstrap.min.css" rel="stylesheet" integrity="sha384-HqaYdAE26lgFCJsUF9TBdbZf7ygr9yPHtxtg37JshqVQi6CCAo6Qvwmgc5xclIiV" crossorigin="anonymous">
  
  
    <!-- Custom styles for this template -->
    <style>
      .container {
        padding-top: 100px;
      }
    </style>
  
  <script data-dapp-detection="">
  (function() {
    let alreadyInsertedMetaTag = false
  
    function __insertDappDetected() {
      if (!alreadyInsertedMetaTag) {
        const meta = document.createElement('meta')
        meta.name = 'dapp-detected'
        document.head.appendChild(meta)
        alreadyInsertedMetaTag = true
      }
    }
  
    if (window.hasOwnProperty('web3')) {
      // Note a closure can't be used for this var because some sites like
      // www.wnyc.org do a second script execution via eval for some reason.
      window.__disableDappDetectionInsertion = true
      // Likely oldWeb3 is undefined and it has a property only because
      // we defined it. Some sites like wnyc.org are evaling all scripts
      // that exist again, so this is protection against multiple calls.
      if (window.web3 === undefined) {
        return
      }
      __insertDappDetected()
    } else {
      var oldWeb3 = window.web3
      Object.defineProperty(window, 'web3', {
        configurable: true,
        set: function (val) {
          if (!window.__disableDappDetectionInsertion)
            __insertDappDetected()
          oldWeb3 = val
        },
        get: function () {
          if (!window.__disableDappDetectionInsertion)
            __insertDappDetected()
          return oldWeb3
        }
      })
    }
  })()</script>
  
</head>
  
  <body>
   
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
      <a class="navbar-brand" href="#">DenunciasApp</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
    
      <div class="collapse navbar-collapse" id="navbarsExampleDefault">
        <ul class="navbar-nav ml-auto">
          <!-- Si el usuario esta logeado se mostrara el dropdown con opciones-->
          <li class="nav-item {% if request.endpoint =='complaint_page.create' %}  active {% endif %}">
            <a class="nav-link" href="{{ url_for('complaint_page.create') }}">Create a Complaint</a>
          </li>
          <li class="nav-item {% if request.endpoint == 'complaint_page.explore' %}active{% endif %}">
            <a class="nav-link" href="{{ url_for('complaint_page.explore') }}">Explore</a>
          </li> 
          {% if session.email %}   
        <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">{{ session.email }}</a>
            <div class="dropdown-menu">
              <a class="dropdown-item" href="{{ url_for('complaint_page.manage') }}">My Complaints</a>
              <a class="dropdown-item" href="{{ url_for('user_page.edit') }}">Edit Profile</a>
              <a class="dropdown-item" href="{{ url_for('user_page.password') }}">Change Password</a>
              
            </div>
          </li>
          <li class="nav-item">
            <a class="dropdown-item" href="{{ url_for('user_page.logout') }}"">Logout</a>
          </li>
            <!-- Si el usuario no esta logeado se mostrara el dropdown basico de login/signup-->
          {% else %}
          <li class="nav-item {% if request.endpoint =='user_page.login' %}  active {% endif %}">
            <a class="nav-link" href="{{ url_for('user_page.login') }}">Log In</a>
          </li>
          <li class="nav-item {% if request.endpoint =='user_page.signup' %}  active {% endif %}">
            <a class="nav-link" href="{{ url_for('user_page.signup') }}">Sign Up</a>
          </li>
          {% endif %}
        </ul>
      </div>
    </nav>
  
    <!-- Page Content -->
    <div class="container">
    
        {% block content%} {% endblock %}
    </div>
  
    <!-- Bootstrap core JavaScript -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
  {% block javascript %}
  {% endblock  %}
  
  
  
  </body></html>

App/templates/googleapi.html
<script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyB8QCFO9a_zsnIJVVK8bsawX-sWrPjMytU&libraries=places&callback=initAutocomplete" async defer></script>

<script>
    function initAutocomplete() {
        // Create the autocomplete object, restricting the search to geographical
        // location types.
        autocomplete = new google.maps.places.Autocomplete(
            /** @type {!HTMLInputElement} */
            (document.getElementById('autocomplete')), {
                types: ['geocode']
            });

        // When the user selects an address from the dropdown, populate the address
        // fields in the form.
        autocomplete.addListener('place_changed', fillInAddress);
    }

    function fillInAddress() {
        // Get the place details from the autocomplete object.
        var place = autocomplete.getPlace();
        document.getElementById('place').value = place.formatted_address;
        document.getElementById('lng').value = place.geometry.location.lng();
        document.getElementById('lat').value = place.geometry.location.lat();
        
    }
</script>